"""initial schema

Revision ID: 628f4eb90317
Revises: 
Create Date: 2026-03-23 04:53:42.498971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628f4eb90317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_video_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('upload_date', sa.String(length=10), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('availability', sa.Enum('AVAILABLE', 'NEEDS_AUTH', 'GEO_BLOCKED', 'PRIVATE', 'REMOVED', 'UNKNOWN', name='entryavailability'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_external_video_id'), 'entries', ['external_video_id'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'PLAYLIST', 'CHANNEL', name='sourcetype'), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('uploader', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_index(op.f('ix_sources_external_id'), 'sources', ['external_id'], unique=False)
    op.create_table('format_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formats_json', sa.JSON(), nullable=False),
    sa.Column('subtitles_json', sa.JSON(), nullable=True),
    sa.Column('chapters_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_format_snapshots_entry_id'), 'format_snapshots', ['entry_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('DOWNLOAD', 'COMPILE', 'RESCAN', name='jobkind'), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=256), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('speed_bps', sa.Integer(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'entry_id')
    )
    op.create_index(op.f('ix_source_entries_entry_id'), 'source_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_source_entries_source_id'), 'source_entries', ['source_id'], unique=False)
    op.create_table('job_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('format_mode', sa.String(length=32), nullable=False),
    sa.Column('format_spec', sa.String(length=256), nullable=False),
    sa.Column('container', sa.String(length=16), nullable=False),
    sa.Column('max_height', sa.Integer(), nullable=True),
    sa.Column('sponsorblock_action', sa.Enum('KEEP', 'MARK_CHAPTERS', 'REMOVE', name='sponsorblockaction'), nullable=False),
    sa.Column('output_dir', sa.String(length=1024), nullable=True),
    sa.Column('cookie_file', sa.String(length=1024), nullable=True),
    sa.Column('output_signature_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_requests_output_signature_hash'), 'job_requests', ['output_signature_hash'], unique=False)
    op.create_table('job_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('REVALIDATE_FORMATS', 'DOWNLOAD_VIDEO', 'DOWNLOAD_AUDIO', 'MERGE', 'SPONSORBLOCK', 'FINALIZE', name='stagetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='stagestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('log_file', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_stages_job_id'), 'job_stages', ['job_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('VIDEO_STREAM', 'AUDIO_STREAM', 'MERGED', 'CLEANED', name='artifactkind'), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('produced_by_stage_id', sa.Uuid(), nullable=True),
    sa.Column('parent_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produced_by_stage_id'], ['job_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_table('archive_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_video_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('output_signature_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('first_downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_records_external_video_id'), 'archive_records', ['external_video_id'], unique=False)
    op.create_index(op.f('ix_archive_records_output_signature_hash'), 'archive_records', ['output_signature_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archive_records_output_signature_hash'), table_name='archive_records')
    op.drop_index(op.f('ix_archive_records_external_video_id'), table_name='archive_records')
    op.drop_table('archive_records')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_job_stages_job_id'), table_name='job_stages')
    op.drop_table('job_stages')
    op.drop_index(op.f('ix_job_requests_output_signature_hash'), table_name='job_requests')
    op.drop_table('job_requests')
    op.drop_index(op.f('ix_source_entries_source_id'), table_name='source_entries')
    op.drop_index(op.f('ix_source_entries_entry_id'), table_name='source_entries')
    op.drop_table('source_entries')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_format_snapshots_entry_id'), table_name='format_snapshots')
    op.drop_table('format_snapshots')
    op.drop_index(op.f('ix_sources_external_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_entries_external_video_id'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
