"""add subscriptions and filters

Revision ID: 841e1f6e41bf
Revises: 628f4eb90317
Create Date: 2026-03-23 05:29:27.028858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841e1f6e41bf'
down_revision: Union[str, None] = '628f4eb90317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_download', sa.Boolean(), nullable=False),
    sa.Column('format_mode', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.Column('sponsorblock_action', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_source_id'), 'subscriptions', ['source_id'], unique=False)
    op.create_table('subscription_filters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('filter_type', sa.Enum('IGNORE_SHORTS', 'MIN_DURATION', 'MAX_DURATION', 'KEYWORD_INCLUDE', 'KEYWORD_EXCLUDE', 'IGNORE_LIVE', name='subscriptionfiltertype'), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_filters_subscription_id'), 'subscription_filters', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_filters_subscription_id'), table_name='subscription_filters')
    op.drop_table('subscription_filters')
    op.drop_index(op.f('ix_subscriptions_source_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
